// 这里记录接口情况


# 博客基本数据 标题 标签 导航 友连
GET http://127.0.0.1:3000/api/init HTTP/1.1
GET http://aming660.cn:3000/api/init HTTP/1.1

# 文章列表 (无筛选)
GET http://127.0.0.1:3000/api/list HTTP/1.1
GET http://aming660.cn:3000/api/list HTTP/1.1
User-Agent: vscode-restclient
Accept-Encoding: gzip
Accept-Charset: utf-8

#  list 分页 (有筛选)
GET http://127.0.0.1:3000/api/list?page=1&type=linux HTTP/1.1
GET http://aming660.cn:3000/api/list?page=1&type=linux HTTP/1.1

#  请求文章接口
GET http://127.0.0.1:3000/api/content?id=5c33058b2af4d740ec008882 HTTP/1.1
GET http://aming660.cn:3000/api/content?id=5c33058b2af4d740ec008882 HTTP/1.1
User-Agent: vscode-restclient
Accept-Encoding: gzip
Accept-Charset: utf-8

POST http://127.0.0.1:3000/api/verCode HTTP/1.1

{
  "name": "sllslsl",
}



GET http://icanhazip.com HTTP/1.1

GET http://ip.cip.cc HTTP/1.1

GET http://ifconfig.co HTTP/1.1